name: first workflow
on:
  push:
    branches:
      - main
jobs:
  initial_job:
    name: testing a first job
    runs-on:  ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v2
  start_server:
      name: tesing a 2nd job
      runs-on: ubuntu-latest
      needs: initial_job
      steps:
        - name : checkout
          uses: actions/checkout@v2
        - name: Install dependencies
          uses: npm install
        - name: Run npm test suite
          uses: npm test
          
        
    
